//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_SubCategory
    {
        public int Id { get; set; }
        public int Category { get; set; }
        public int SubCategory { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual SubCategory SubCategory1 { get; set; }
    }
}
