//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public string ImagePath { get; set; }
        public int ParentSubCategory { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual SubCategory SubCategory { get; set; }
    }
}
