//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdminPanelEntities : DbContext
    {
        public AdminPanelEntities()
            : base("name=AdminPanelEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
        
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Category_SubCategory> Category_SubCategory { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
    }
}
